### ISSUE TITLE
Decompiling source

### ISSUE THREAD

**Issue by HenrySlawniak** [MCME/NoChunk#2]
This repo contains original source code of mine that was decompiled, renamed, repackaged, and then uploaded without my permission. I would appreciate it if it was removed.

**Comment by DonoA** [comment]
Very valid, @q220 if you could please remove this repo.

**Comment by DonoA** [comment]
resolved, all your code has been removed.

**Comment by HenrySlawniak** [comment]
Technically, it is still in the tree...
